### ISSUE TITLE
Feature Request: Compare offline tally with json or endpoint

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/catalyst-toolbox#15]
It would be great if catalyst-toolbox could compare tally output from `recover tally ...` command with either json file or endpoint /vote/active/plans.  Right now, i need to use some website to do that (http://www.jsondiff.com/) since attributes in both files are differently sorter. I realize it's not a big manual effort to do that, but my plan is to use it in automation. 

Example:

```
cargo run -- recover tally --block0-url https://dryrun-servicing-station.vit.iohk.io/api/v0/block0 --output-format "json" --logs-path "C:\Work\vit-dryrun\persistent_log\dryrun4\fragments"  --diff-with-path C:\Work\vit-dryrun\persistent_log\dryrun4\offline.json
```

or 

```
cargo run -- recover tally --block0-url https://dryrun-servicing-station.vit.iohk.io/api/v0/block0 --output-format "json" --logs-path "C:\Work\vit-dryrun\persistent_log\dryrun4\fragments"  --diff-with-url http://{}/api/v0/vote/active/plans
```

**Comment by eugene-babichenko** [comment]
I think that outputting to JSON that can be then passed to external tools must be sufficient. For example, you can employ something like `jq`.

**Comment by Zeegomo** [comment]
Yep, we discussed with @dkijania and this is no longer needed
