### ISSUE TITLE
Fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/catalyst-toolbox#182]
Ubuntu has upgraded to libssl3. In the pre-built binaries, all the links are to libssl.so.1.1 instead of libssl.so.3 and also libcrypto.so.1.1 instead of libcrypto.so.3.

This entire build structure looks completely fragile as it's pointing to branches of a dozen other projects. These should be tags or specific commits.

I'm not able to build this code on an Ubuntu 22.04 machine running rust 1.70.

**Comment by AndrewWestberg** [comment]
got it to work on the catalyst-fund9.1 branch.

**Comment by rphair** [comment]
Thanks @AndrewWestberg - builds for me too.  We would have been in a tough spot without knowing that other branch was there.  On a typical Ubuntu 22.04 server installation it only requires installing package `libssl-dev` to compile successfully.

**Comment by kukkok3** [comment]
Hi, this repo is not manteined anymore, please refer to https://github.com/input-output-hk/catalyst-core. Catalyst-toolbox is here https://github.com/input-output-hk/catalyst-core/tree/main/src/catalyst-toolbox
