### ISSUE TITLE
Static ssl lib

### ISSUE THREAD

**Issue by Scitz0** [input-output-hk/catalyst-toolbox#185]
Hi,

catalyst-toolbox doesn't currently run on my system (Debian 12) due to:
```
error while loading shared libraries: libssl.so.1.1
```
Could SSL please be statically built into the binary?
I would like to add catalyst support into CNTools to display QR code using catalyst-toolbox but having users build from source or install old SSL libraries on the system is a no-go. 
I think the solution is to build with `OPENSSL_STATIC=yes` and include openssl build library in path while building.

**Comment by rdlrt** [comment]
Having to either compile openssl on user machine (to an alternate location just for this tool) OR to use an outdated version of openssl that has known security vulnerabilities are both not acceptable on machines where user keys could be present - best to use static binaries.

**Comment by Scitz0** [comment]
I see that repo is not maintained. Closing issue.
