### ISSUE TITLE
Add date range for download logs from sentry

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/catalyst-toolbox#23]
Please add possibility to provide data ranges (both sides) to download sentry log command:

Date example:

`"2021-06-03T11:45:34+00:00"`

usage example:

`catalyst-toolbox logs sentry download --out ./out.log --url .... --token ..... --start  2021-06-03T11:45:34+00:00--end 2021-06-03T12:45:34+00:00"`

**Comment by danielSanchezQ** [comment]
Added to #21

**Comment by danielSanchezQ** [comment]
Done in #26
